POST http://localhost:3000/invocations
Content-Type: application/json

{
  "prompt": "tell me a joke"
}

###

POST https://hello-vercel-ai-374286597410.us-central1.run.app/invocations
Content-Type: application/json

{
  "prompt": "tell me a joke"
}
