POST http://localhost:3000/invocations
Content-Type: application/json

{
  "prompt": "tell me a joke"
}

###

POST https://hello-vercel-cou0wd4tk-james-jameswardcos-projects.vercel.app/api/agent
Content-Type: application/json

{
  "prompt": "tell me a joke"
}
